"""Current SQLAlchemy metadata exposed to repositories and Alembic autogeneration."""

from packages.persistence.baseline_v0001 import (
    active_pointer,
    artifact,
    artifact_state_transition,
    artifact_version,
    asset_rights,
    audit_event,
    automation_policy,
    blob,
    command,
    config_snapshot,
    correction,
    dependency,
    invalidation_decision,
    metadata,
    outbox_event,
    project,
    publication_pointer,
    resource_profile,
    review_decision,
    review_request,
    rights_manifest,
    run,
    stage_execution,
    variant,
)

__all__ = [
    "active_pointer",
    "artifact",
    "artifact_state_transition",
    "artifact_version",
    "asset_rights",
    "audit_event",
    "automation_policy",
    "blob",
    "command",
    "config_snapshot",
    "correction",
    "dependency",
    "invalidation_decision",
    "metadata",
    "outbox_event",
    "project",
    "publication_pointer",
    "resource_profile",
    "review_decision",
    "review_request",
    "rights_manifest",
    "run",
    "stage_execution",
    "variant",
]
